package src.Interfaces;

import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import src.Modelo.Equipos.EquipoFantasia;
import src.Modelo.Jugadores.Jugador;
import src.Vista.App;

/**
 *
 * @author miguelgomez
 */

public class ComprarJugadores extends javax.swing.JFrame {

        private String[] stringsForJList;

        public String posicionJugador;
        public ArrayList<Jugador> jugadores;

        public ComprarJugadores(String posicionJugador) {

                this.posicionJugador = posicionJugador;
                jugadores = App.getJugadoresPorPosicion(this.posicionJugador);
                stringsForJList = new String[jugadores.size()];
                for (int i = 0; i < jugadores.size(); i++) {
                        stringsForJList[i] = jugadores.get(i).getNombre();
                }

                initComponents();

                NombreJugador.setText("-");
                EquipoJugador.setText("-");
                CostoJugador.setText("-");

                jListJugadores.setModel(new javax.swing.AbstractListModel<String>() {
                        String[] strings = stringsForJList;

                        public int getSize() {
                                return strings.length;
                        }

                        public String getElementAt(int i) {
                                return strings[i];
                        }
                });

                jListJugadores.addListSelectionListener(new ListSelectionListener() {

                        @Override
                        public void valueChanged(ListSelectionEvent e) {
                                NombreJugador.setText(jListJugadores.getSelectedValue());
                                EquipoJugador.setText(
                                                App.getEquipoPorJugador(jListJugadores.getSelectedValue()).getNombre());
                                CostoJugador.setText(
                                                App.getJugadorPorNombre(jListJugadores.getSelectedValue()).getPrecio()
                                                                .toString());
                        }
                });

                PosicionJugador.setText(posicionJugador);

                presupuestoLbl.setText("Presupuesto: " + App.participanteActual.getEquipo().getPresupuesto());

                this.setVisible(true);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                PanelLeft = new javax.swing.JPanel();
                PanelTop = new javax.swing.JPanel();
                presupuestoLbl = new javax.swing.JLabel();
                PosicionJugador = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                exitLblBtn = new javax.swing.JLabel();
                PanelRight = new javax.swing.JPanel();
                PanelCenter = new javax.swing.JPanel();
                PanelJugadorComprar = new javax.swing.JPanel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                NombreJugador = new javax.swing.JLabel();
                EquipoJugador = new javax.swing.JLabel();
                CostoJugador = new javax.swing.JLabel();
                jLabel9 = new javax.swing.JLabel();
                jScrollPane2 = new javax.swing.JScrollPane();
                jListJugadores = new javax.swing.JList<>();
                ComprarJugadorBtn = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setUndecorated(true);
                setPreferredSize(new java.awt.Dimension(1334, 806));

                PanelLeft.setBackground(new java.awt.Color(0, 51, 51));

                javax.swing.GroupLayout PanelLeftLayout = new javax.swing.GroupLayout(PanelLeft);
                PanelLeft.setLayout(PanelLeftLayout);
                PanelLeftLayout.setHorizontalGroup(
                                PanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 100, Short.MAX_VALUE));
                PanelLeftLayout.setVerticalGroup(
                                PanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 594, Short.MAX_VALUE));

                getContentPane().add(PanelLeft, java.awt.BorderLayout.LINE_START);

                PanelTop.setBackground(new java.awt.Color(0, 153, 153));

                presupuestoLbl.setFont(new java.awt.Font("Poiret One", 1, 36)); // NOI18N
                presupuestoLbl.setForeground(new java.awt.Color(255, 255, 255));
                presupuestoLbl.setText("Presupuesto: 15000");

                PosicionJugador.setFont(new java.awt.Font("Poiret One", 1, 36)); // NOI18N
                PosicionJugador.setForeground(new java.awt.Color(255, 255, 255));
                PosicionJugador.setText("Arquero");

                jLabel2.setFont(new java.awt.Font("Poiret One", 1, 36)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                jLabel2.setText("Comprar Jugadores:");

                exitLblBtn.setFont(new java.awt.Font("Poiret One", 1, 48)); // NOI18N
                exitLblBtn.setForeground(new java.awt.Color(255, 255, 255));
                exitLblBtn.setText("X");
                exitLblBtn.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                exitLblBtnMouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout PanelTopLayout = new javax.swing.GroupLayout(PanelTop);
                PanelTop.setLayout(PanelTopLayout);
                PanelTopLayout.setHorizontalGroup(
                                PanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(PanelTopLayout.createSequentialGroup()
                                                                .addGap(110, 110, 110)
                                                                .addComponent(presupuestoLbl)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTopLayout
                                                                .createSequentialGroup()
                                                                .addGap(32, 457, Short.MAX_VALUE)
                                                                .addComponent(PosicionJugador,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                780,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(33, 33, 33)
                                                                .addComponent(exitLblBtn)
                                                                .addGap(28, 28, 28))
                                                .addGroup(PanelTopLayout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(PanelTopLayout.createSequentialGroup()
                                                                                .addGap(110, 110, 110)
                                                                                .addComponent(jLabel2)
                                                                                .addContainerGap(875,
                                                                                                Short.MAX_VALUE))));
                PanelTopLayout.setVerticalGroup(
                                PanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(PanelTopLayout.createSequentialGroup()
                                                                .addGap(28, 28, 28)
                                                                .addGroup(PanelTopLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(PosicionJugador)
                                                                                .addComponent(exitLblBtn))
                                                                .addGap(9, 9, 9)
                                                                .addComponent(presupuestoLbl)
                                                                .addContainerGap(49, Short.MAX_VALUE))
                                                .addGroup(PanelTopLayout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(PanelTopLayout.createSequentialGroup()
                                                                                .addGap(41, 41, 41)
                                                                                .addComponent(jLabel2)
                                                                                .addContainerGap(102,
                                                                                                Short.MAX_VALUE))));

                getContentPane().add(PanelTop, java.awt.BorderLayout.PAGE_START);

                PanelRight.setBackground(new java.awt.Color(0, 51, 51));

                javax.swing.GroupLayout PanelRightLayout = new javax.swing.GroupLayout(PanelRight);
                PanelRight.setLayout(PanelRightLayout);
                PanelRightLayout.setHorizontalGroup(
                                PanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 100, Short.MAX_VALUE));
                PanelRightLayout.setVerticalGroup(
                                PanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 594, Short.MAX_VALUE));

                getContentPane().add(PanelRight, java.awt.BorderLayout.LINE_END);

                PanelCenter.setBackground(new java.awt.Color(204, 204, 204));

                PanelJugadorComprar.setBackground(new java.awt.Color(255, 255, 255));
                PanelJugadorComprar
                                .setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0,
                                                new java.awt.Color(0, 0, 0)));

                jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                jLabel4.setText("Equipo:");

                jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                jLabel5.setText("Jugador:");

                NombreJugador.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                NombreJugador.setText("Pedri");

                EquipoJugador.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                EquipoJugador.setText("FC");

                CostoJugador.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                CostoJugador.setText("1200");

                jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                jLabel9.setText("Costo:");

                javax.swing.GroupLayout PanelJugadorComprarLayout = new javax.swing.GroupLayout(PanelJugadorComprar);
                PanelJugadorComprar.setLayout(PanelJugadorComprarLayout);
                PanelJugadorComprarLayout.setHorizontalGroup(
                                PanelJugadorComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(PanelJugadorComprarLayout.createSequentialGroup()
                                                                .addGroup(PanelJugadorComprarLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(PanelJugadorComprarLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(55, 55, 55)
                                                                                                .addGroup(PanelJugadorComprarLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jLabel4)
                                                                                                                .addComponent(jLabel9))
                                                                                                .addGap(25, 25, 25)
                                                                                                .addComponent(CostoJugador))
                                                                                .addGroup(PanelJugadorComprarLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(159, 159, 159)
                                                                                                .addGroup(PanelJugadorComprarLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(EquipoJugador)
                                                                                                                .addComponent(NombreJugador))))
                                                                .addContainerGap(491, Short.MAX_VALUE))
                                                .addGroup(
                                                                PanelJugadorComprarLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(PanelJugadorComprarLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(55, 55, 55)
                                                                                                .addComponent(jLabel5)
                                                                                                .addContainerGap(559,
                                                                                                                Short.MAX_VALUE))));
                PanelJugadorComprarLayout.setVerticalGroup(
                                PanelJugadorComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(PanelJugadorComprarLayout.createSequentialGroup()
                                                                .addGap(16, 16, 16)
                                                                .addComponent(NombreJugador)
                                                                .addGap(17, 17, 17)
                                                                .addGroup(PanelJugadorComprarLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel4)
                                                                                .addComponent(EquipoJugador))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(PanelJugadorComprarLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel9)
                                                                                .addComponent(CostoJugador))
                                                                .addContainerGap(107, Short.MAX_VALUE))
                                                .addGroup(
                                                                PanelJugadorComprarLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(PanelJugadorComprarLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(16, 16, 16)
                                                                                                .addComponent(jLabel5)
                                                                                                .addContainerGap(206,
                                                                                                                Short.MAX_VALUE))));

                jListJugadores
                                .setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0,
                                                new java.awt.Color(0, 0, 0)));
                jListJugadores.setFont(new java.awt.Font("Poiret One", 1, 36)); // NOI18N
                jListJugadores.setModel(new javax.swing.AbstractListModel<String>() {
                        String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };

                        public int getSize() {
                                return strings.length;
                        }

                        public String getElementAt(int i) {
                                return strings[i];
                        }
                });
                jScrollPane2.setViewportView(jListJugadores);

                ComprarJugadorBtn.setBackground(new java.awt.Color(255, 255, 255));
                ComprarJugadorBtn.setFont(new java.awt.Font("Segoe UI", 0, 70)); // NOI18N
                ComprarJugadorBtn.setForeground(new java.awt.Color(0, 0, 0));
                ComprarJugadorBtn.setText("Comprar");
                ComprarJugadorBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ComprarJugadorBtnActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout PanelCenterLayout = new javax.swing.GroupLayout(PanelCenter);
                PanelCenter.setLayout(PanelCenterLayout);
                PanelCenterLayout.setHorizontalGroup(
                                PanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(PanelCenterLayout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addGroup(PanelCenterLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                .addComponent(PanelJugadorComprar,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(ComprarJugadorBtn,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jScrollPane2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                370,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(13, Short.MAX_VALUE)));
                PanelCenterLayout.setVerticalGroup(
                                PanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(PanelCenterLayout.createSequentialGroup()
                                                                .addGap(23, 23, 23)
                                                                .addGroup(PanelCenterLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                .addComponent(jScrollPane2)
                                                                                .addGroup(PanelCenterLayout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(PanelJugadorComprar,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(ComprarJugadorBtn,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                275,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addContainerGap(10, Short.MAX_VALUE)));

                getContentPane().add(PanelCenter, java.awt.BorderLayout.CENTER);

                pack();
        }// </editor-fold>

        private void ComprarJugadorBtnActionPerformed(java.awt.event.ActionEvent evt) {

                // equipo fantasia del ususario
                EquipoFantasia equipoUsuario = App.participanteActual.getEquipo();
                
                // sacar jugador
                Jugador jugadorAComprar = App.getJugadorPorNombre(jListJugadores.getSelectedValue());

                // verificar que el jugador no este ya en el equipo
                ArrayList<Jugador> jugadoresEnEquipoFantasia = App.participanteActual.getEquipo().getJugadores();

                boolean sePuedeComprar = true;

                if(jugadoresEnEquipoFantasia.contains(jugadorAComprar)){
                        JOptionPane.showMessageDialog(null,"Ya tienes este jugador en tu equipo !");
                }else{
                       

                       
                // verificar que el presupuesto sea suficiente para comprar el jugador
                double nuevoPresupuesto = App.participanteActual.getEquipo().getPresupuesto()
                                - jugadorAComprar.getPrecio();

                if (nuevoPresupuesto <= 0) {
                        JOptionPane.showMessageDialog(null,
                                        "No tienes suficiente dinero para anadir este jugador a tu equipo");
                } else {
                        //verificar cantidad maxima de jugadores de cada tipo
                        if (jugadorAComprar.getPosicion().equals("arquero")){
                                if(equipoUsuario.getCantArqueros() >= 2){
                                        sePuedeComprar = false;
                                }else{
                                        equipoUsuario.setCantArqueros(equipoUsuario.getCantArqueros() + 1);
                                }
                        }else if (jugadorAComprar.getPosicion().equals("defensa")) {
                                if (equipoUsuario.getCantDefensores() >= 5) {
                                        sePuedeComprar = false;
                                }else{
                                         equipoUsuario.setCantDefensores(equipoUsuario.getCantDefensores() + 1);
                                }
                        }else if (jugadorAComprar.getPosicion().equals("mediocampista")) {
                                if (equipoUsuario.getCantMediocampistas() >= 5) {
                                        sePuedeComprar = false;
                                }else{
                                        equipoUsuario.setCantMediocampistas(equipoUsuario.getCantMediocampistas() + 1); 
                                }
                        } else if (jugadorAComprar.getPosicion().equals("delantero")) {
                                if (equipoUsuario.getCantDelanteros() >= 2) {
                                        sePuedeComprar = false;
                                }else{
                                        equipoUsuario.setCantDelanteros(equipoUsuario.getCantDelanteros() + 1);
                                }
                        }

                        if(sePuedeComprar){
                        // actualizar presupuesto
                        App.participanteActual.getEquipo().setPresupuesto(nuevoPresupuesto);
                        // actualizar label presupuesto
                        presupuestoLbl.setText(
                                        "Presupuesto: " + App.participanteActual.getEquipo()
                                                        .getPresupuesto());

                        // anadir jugador a equipo fantasia
                        ArrayList<Jugador> jugadores = App.participanteActual.getEquipo()
                                        .getJugadores();
                        jugadores.add(jugadorAComprar);
                        App.participanteActual.getEquipo().setJugadores(jugadores);

                        // decirle al usuario que el jugador se ha anadido
                        JOptionPane.showMessageDialog(null,
                                        "jugador se ha anadido a tu equipo de fantasia");
                        
                        }
                        else{
                                JOptionPane.showMessageDialog(null, "No puedes tener mas jugadores en esta posicion. Vende uno primero e intenta comprarlo subsecuentemente.");
                        }
                        
                        
                }
        }
 
               

                

        }

        private void exitLblBtnMouseClicked(java.awt.event.MouseEvent evt) {
                this.dispose();
                new UserFrame();
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(ComprarJugadores.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(ComprarJugadores.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(ComprarJugadores.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(ComprarJugadores.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                }
                // </editor-fold>
                // </editor-fold>

                /* Create and display the form */
                // java.awt.EventQueue.invokeLater(new Runnable() {
                // public void run() {
                // new ComprarJugadores().setVisible(true);
                // }
                // });
        }

        // Variables declaration - do not modify
        private javax.swing.JButton ComprarJugadorBtn;
        private javax.swing.JLabel CostoJugador;
        private javax.swing.JLabel EquipoJugador;
        private javax.swing.JLabel NombreJugador;
        private javax.swing.JPanel PanelCenter;
        private javax.swing.JPanel PanelJugadorComprar;
        private javax.swing.JPanel PanelLeft;
        private javax.swing.JPanel PanelRight;
        private javax.swing.JPanel PanelTop;
        private javax.swing.JLabel PosicionJugador;
        private javax.swing.JLabel exitLblBtn;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JList<String> jListJugadores;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JLabel presupuestoLbl;
        // End of variables declaration
}
